# Generated by Django 4.0.2 on 2024-01-01 07:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texeclientapp', '0002_alter_registration_joindate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='joindate',
            field=models.DateField(default=datetime.date(2024, 1, 1), null=True),
        ),
    ]
