# Generated by Django 4.0.2 on 2024-01-01 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('texeclientapp', '0003_alter_registration_joindate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OtherProjectModel',
        ),
    ]
