# Generated by Django 4.0.2 on 2023-12-22 12:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('texecrmapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='joindate',
            field=models.DateField(default=datetime.date(2023, 12, 22), null=True),
        ),
        migrations.CreateModel(
            name='complaint_service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('date_register', models.DateField(default=datetime.date(2023, 12, 22))),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('users', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='texecrmapp.users')),
            ],
        ),
    ]
