# Generated by Django 4.0.2 on 2023-12-22 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texecrmapp', '0002_alter_users_joindate_complaint_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint_service',
            name='regno',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
