# Generated by Django 4.0.2 on 2023-12-27 06:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texecrmapp', '0004_users_designation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='complaint',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='orders',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='preformance',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='complaint_service',
            name='date_register',
            field=models.DateField(default=datetime.date(2023, 12, 27)),
        ),
        migrations.AlterField(
            model_name='users',
            name='joindate',
            field=models.DateField(default=datetime.date(2023, 12, 27), null=True),
        ),
    ]
