# Generated by Django 4.0.2 on 2023-12-30 07:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texecrmapp', '0006_alter_complaint_service_date_register_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint_service',
            name='date_register',
            field=models.DateField(default=datetime.date(2023, 12, 30)),
        ),
        migrations.AlterField(
            model_name='users',
            name='joindate',
            field=models.DateField(default=datetime.date(2023, 12, 30), null=True),
        ),
        migrations.DeleteModel(
            name='events',
        ),
    ]
